# Generated by Django 2.2.16 on 2022-08-18 08:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220815_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmation_code',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(
                max_length=150,
                unique=True,
                validators=[django.core.validators.RegexValidator(
                    message='''Имя пользователя должно быть не длинее 
                150 символов.Допустимы буквы, цифры и символы: @/./+/-/_.''',
                    regex='^[\\w.@+-]+$')]),
        ),
    ]
